// filepath: apps/web-display/src/pages/ledger/Ledger.jsx

import { useState, useEffect, useCallback } from "react";
import {
  Typography,
  Box,
  Card,
  CardContent,
  Grid,
  TextField,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  ToggleButton,
  ToggleButtonGroup,
  CircularProgress,
  Divider,
} from "@mui/material";
import "@fontsource/almarai";
import axios from "axios";
import { toast } from "react-hot-toast";
import { API_LEDGER_URL } from "../../apiconfig";

// Only the categories that make sense for a manual entry
// (LAB_COST, LAB_REVENUE, DOCTOR_PAYOUT are auto-generated by their workflows)
const MANUAL_CATEGORIES = [
  { value: "PATIENT_FEE", label: "رسوم مرضى" },
  { value: "SERVICE_FEE", label: "رسوم خدمات" },
  { value: "CHARITY_EXPENSE", label: "نفقات تغطية" },
  { value: "GENERAL_EXPENSE", label: "مصاريف عامة" },
];

const ALL_CATEGORY_LABELS = {
  PATIENT_FEE: "رسوم مرضى",
  SERVICE_FEE: "رسوم خدمات",
  DOCTOR_PAYOUT: "مدفوعات أطباء",
  LAB_COST: "تكلفة مختبر",
  LAB_REVENUE: "إيرادات مختبر",
  CHARITY_EXPENSE: "نفقات تغطية",
  GENERAL_EXPENSE: "مصاريف عامة",
};

const CATEGORY_CHIP_COLOR = {
  PATIENT_FEE: "primary",
  SERVICE_FEE: "info",
  DOCTOR_PAYOUT: "warning",
  LAB_COST: "error",
  LAB_REVENUE: "success",
  CHARITY_EXPENSE: "error",
  GENERAL_EXPENSE: "default",
};

export default function Ledger() {
  // ── Form state ──────────────────────────────────────────────
  const [amount, setAmount] = useState("");
  const [isOutflow, setIsOutflow] = useState(true);
  const [category, setCategory] = useState("GENERAL_EXPENSE");
  const [description, setDescription] = useState("");
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [submitting, setSubmitting] = useState(false);

  // ── Filter / list state ─────────────────────────────────────
  const [transactions, setTransactions] = useState([]);
  const [loadingTx, setLoadingTx] = useState(false);
  const [filterCategory, setFilterCategory] = useState("");
  const [filterStart, setFilterStart] = useState("");
  const [filterEnd, setFilterEnd] = useState("");

  const fetchTransactions = useCallback(async () => {
    setLoadingTx(true);
    try {
      const params = {};
      if (filterCategory) params.category = filterCategory;
      if (filterStart) params.startDate = filterStart;
      if (filterEnd) params.endDate = filterEnd;
      const res = await axios.get(API_LEDGER_URL, { params });
      setTransactions(res.data);
    } catch {
      toast.error("فشل تحميل المعاملات");
    } finally {
      setLoadingTx(false);
    }
  }, [filterCategory, filterStart, filterEnd]);

  useEffect(() => {
    fetchTransactions();
  }, [fetchTransactions]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!amount || isNaN(Number(amount)) || Number(amount) <= 0) {
      toast.error("يرجى إدخال مبلغ صحيح");
      return;
    }
    if (!description.trim()) {
      toast.error("يرجى إدخال وصف للمعاملة");
      return;
    }

    setSubmitting(true);
    try {
      await axios.post(API_LEDGER_URL, {
        amount: Number(amount),
        isOutflow,
        category,
        description: description.trim(),
        date: date || undefined,
      });
      toast.success("تم تسجيل المعاملة في الدفتر");
      setAmount("");
      setDescription("");
      setDate(new Date().toISOString().slice(0, 10));
      setCategory("GENERAL_EXPENSE");
      setIsOutflow(true);
      fetchTransactions();
    } catch {
      toast.error("فشل تسجيل المعاملة");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div style={{ padding: "2rem", maxWidth: "960px", margin: "0 auto" }}>
      <Typography
        variant="h4"
        gutterBottom
        sx={{ fontFamily: "Almarai, sans-serif" }}
      >
        الدفتر المالي
      </Typography>

      {/* ── NEW ENTRY FORM ─────────────────────────────────── */}
      <Card sx={{ mb: 4, bgcolor: "#f8fafc" }}>
        <CardContent>
          <Typography
            variant="h6"
            sx={{ fontFamily: "Almarai, sans-serif", mb: 2 }}
            gutterBottom
          >
            تسجيل معاملة يدوية
          </Typography>

          <Box component="form" onSubmit={handleSubmit}>
            <Grid container spacing={3}>
              {/* Direction toggle */}
              <Grid item xs={12} sm={3}>
                <Typography
                  variant="caption"
                  sx={{
                    fontFamily: "Almarai, sans-serif",
                    color: "text.secondary",
                    display: "block",
                    mb: 0.5,
                  }}
                >
                  نوع المعاملة
                </Typography>
                <ToggleButtonGroup
                  value={isOutflow ? "outflow" : "inflow"}
                  exclusive
                  onChange={(_, v) => {
                    if (v !== null) setIsOutflow(v === "outflow");
                  }}
                  size="small"
                  fullWidth
                >
                  <ToggleButton
                    value="outflow"
                    sx={{
                      fontFamily: "Almarai, sans-serif",
                      "&.Mui-selected": {
                        bgcolor: "#fee2e2",
                        color: "error.dark",
                        "&:hover": { bgcolor: "#fecaca" },
                      },
                    }}
                  >
                    صادر
                  </ToggleButton>
                  <ToggleButton
                    value="inflow"
                    sx={{
                      fontFamily: "Almarai, sans-serif",
                      "&.Mui-selected": {
                        bgcolor: "#dcfce7",
                        color: "success.dark",
                        "&:hover": { bgcolor: "#bbf7d0" },
                      },
                    }}
                  >
                    وارد
                  </ToggleButton>
                </ToggleButtonGroup>
              </Grid>

              {/* Category */}
              <Grid item xs={12} sm={3}>
                <FormControl fullWidth>
                  <InputLabel sx={{ fontFamily: "Almarai, sans-serif" }}>
                    الفئة
                  </InputLabel>
                  <Select
                    value={category}
                    label="الفئة"
                    onChange={(e) => setCategory(e.target.value)}
                  >
                    {MANUAL_CATEGORIES.map((c) => (
                      <MenuItem key={c.value} value={c.value}>
                        <Typography sx={{ fontFamily: "Almarai, sans-serif" }}>
                          {c.label}
                        </Typography>
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>

              {/* Amount */}
              <Grid item xs={12} sm={3}>
                <TextField
                  fullWidth
                  required
                  label="المبلغ (ل.ل)"
                  type="number"
                  inputProps={{ min: 1 }}
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                />
              </Grid>

              {/* Date */}
              <Grid item xs={12} sm={3}>
                <TextField
                  fullWidth
                  label="التاريخ"
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>

              {/* Description */}
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  required
                  label="الوصف"
                  placeholder="مثال: فاتورة كهرباء، مستلزمات مكتبية، إصلاح جهاز..."
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  inputProps={{ style: { fontFamily: "Almarai, sans-serif" } }}
                />
              </Grid>
            </Grid>

            <Button
              type="submit"
              variant="contained"
              size="large"
              disabled={submitting}
              color={isOutflow ? "error" : "success"}
              sx={{ mt: 3 }}
            >
              <Typography sx={{ fontFamily: "Almarai, sans-serif" }}>
                {submitting
                  ? "جاري التسجيل..."
                  : `تسجيل ${isOutflow ? "مصروف" : "إيراد"}`}
              </Typography>
            </Button>
          </Box>
        </CardContent>
      </Card>

      {/* ── FILTERS ────────────────────────────────────────── */}
      <Card sx={{ mb: 3 }} variant="outlined">
        <CardContent>
          <Typography
            variant="subtitle1"
            sx={{ fontFamily: "Almarai, sans-serif", mb: 2, fontWeight: 600 }}
          >
            تصفية السجلات
          </Typography>
          <Grid container spacing={2} alignItems="center">
            <Grid item xs={12} sm={3}>
              <FormControl fullWidth size="small">
                <InputLabel sx={{ fontFamily: "Almarai, sans-serif" }}>
                  الفئة
                </InputLabel>
                <Select
                  value={filterCategory}
                  label="الفئة"
                  onChange={(e) => setFilterCategory(e.target.value)}
                >
                  <MenuItem value="">
                    <Typography sx={{ fontFamily: "Almarai, sans-serif" }}>
                      الكل
                    </Typography>
                  </MenuItem>
                  {Object.entries(ALL_CATEGORY_LABELS).map(([val, label]) => (
                    <MenuItem key={val} value={val}>
                      <Typography sx={{ fontFamily: "Almarai, sans-serif" }}>
                        {label}
                      </Typography>
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} sm={3}>
              <TextField
                fullWidth
                size="small"
                label="من تاريخ"
                type="date"
                value={filterStart}
                onChange={(e) => setFilterStart(e.target.value)}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>
            <Grid item xs={12} sm={3}>
              <TextField
                fullWidth
                size="small"
                label="إلى تاريخ"
                type="date"
                value={filterEnd}
                onChange={(e) => setFilterEnd(e.target.value)}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>
            <Grid item xs={12} sm={3}>
              <Button
                variant="outlined"
                fullWidth
                onClick={() => {
                  setFilterCategory("");
                  setFilterStart("");
                  setFilterEnd("");
                }}
              >
                <Typography sx={{ fontFamily: "Almarai, sans-serif" }}>
                  إعادة تعيين
                </Typography>
              </Button>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* ── TRANSACTIONS TABLE ──────────────────────────────── */}
      {loadingTx ? (
        <Box sx={{ display: "flex", justifyContent: "center", py: 6 }}>
          <CircularProgress />
        </Box>
      ) : transactions.length === 0 ? (
        <Typography
          sx={{
            fontFamily: "Almarai, sans-serif",
            color: "text.secondary",
            textAlign: "center",
            py: 4,
          }}
        >
          لا توجد معاملات تطابق الفلتر المحدد
        </Typography>
      ) : (
        <TableContainer component={Paper} variant="outlined">
          <Table size="small">
            <TableHead>
              <TableRow sx={{ bgcolor: "#f0f4f8" }}>
                <TableCell>
                  <Typography
                    variant="subtitle2"
                    sx={{ fontFamily: "Almarai, sans-serif" }}
                  >
                    التاريخ
                  </Typography>
                </TableCell>
                <TableCell>
                  <Typography
                    variant="subtitle2"
                    sx={{ fontFamily: "Almarai, sans-serif" }}
                  >
                    الوصف
                  </Typography>
                </TableCell>
                <TableCell align="center">
                  <Typography
                    variant="subtitle2"
                    sx={{ fontFamily: "Almarai, sans-serif" }}
                  >
                    الفئة
                  </Typography>
                </TableCell>
                <TableCell align="center">
                  <Typography
                    variant="subtitle2"
                    sx={{ fontFamily: "Almarai, sans-serif" }}
                  >
                    النوع
                  </Typography>
                </TableCell>
                <TableCell align="right">
                  <Typography
                    variant="subtitle2"
                    sx={{ fontFamily: "Almarai, sans-serif" }}
                  >
                    المبلغ (ل.ل)
                  </Typography>
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {transactions.map((tx) => (
                <TableRow key={tx.id} hover>
                  <TableCell>
                    <Typography
                      variant="body2"
                      color="text.secondary"
                      sx={{ fontFamily: "Almarai, sans-serif" }}
                    >
                      {new Date(tx.date).toLocaleDateString("ar-LB", {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                      })}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography sx={{ fontFamily: "Almarai, sans-serif" }}>
                      {tx.description}
                    </Typography>
                  </TableCell>
                  <TableCell align="center">
                    <Chip
                      label={ALL_CATEGORY_LABELS[tx.category] ?? tx.category}
                      color={CATEGORY_CHIP_COLOR[tx.category] ?? "default"}
                      size="small"
                      sx={{ fontFamily: "Almarai, sans-serif" }}
                    />
                  </TableCell>
                  <TableCell align="center">
                    <Chip
                      label={tx.isOutflow ? "صادر" : "وارد"}
                      color={tx.isOutflow ? "error" : "success"}
                      variant="outlined"
                      size="small"
                      sx={{ fontFamily: "Almarai, sans-serif" }}
                    />
                  </TableCell>
                  <TableCell align="right">
                    <Typography
                      fontWeight={600}
                      sx={{
                        color: tx.isOutflow ? "error.dark" : "success.dark",
                      }}
                    >
                      {tx.isOutflow ? "−" : "+"}
                      {Number(tx.amount).toLocaleString()}
                    </Typography>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      )}
    </div>
  );
}
