## Kulala post request handler

## Test PUT request on doctor settings
PUT http://localhost:4000/api/reception/doctors/1/settings
content-type: application/json

{
  "perPatientFee": 15,
  "perVisitFee": 20,
  "serviceSplits": [{ "serviceId": "...", "splitType": "FLAT", "splitValue": 5 }]
}

### Test Health 
GET http://localhost:4000/health

### TEST ADDING NEW DOCTOR
POST http://localhost:4000/api/reception/doctors/new
content-type: application/json

{
  "name": "Dr. John Doe",
  "perPatientFee": 10,
  "perVisitFee": 15,
  "serviceSplits": [
    { "serviceId": "service1", "splitType": "FLAT", "splitValue": 10 },
    { "serviceId": "service2", "splitType": "PERCENT", "splitValue": 0.6 }
  ]
}

### GET SERVICES
GET http://localhost:4000/api/reception/services

### GET ALL DOCTORS
GET http://localhost:4000/api/reception/doctors

@id=ec99ee87-8876-4c9c-86fb-24b5db56497f

#### GET DOCTOR BY ID
GET http://localhost:4000/api/reception/doctors/{{id}}
