// filepath: apps/backend/src/services/ledgerService.js

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

/**
 * Records a manual ledger transaction (e.g. utility bills, office/kitchen
 * supplies, medical equipment, repairs, or any other general expense/income
 * that isn't auto-generated by the billing or lab workflows).
 */
async function createTransaction({
  amount,
  isOutflow,
  category,
  description,
  date,
}) {
  return prisma.ledgerTransaction.create({
    data: {
      amount,
      isOutflow,
      category,
      description,
      ...(date ? { date: new Date(date) } : {}),
    },
  });
}

/**
 * Lists ledger transactions, optionally filtered by date range and/or category.
 */
async function listTransactions({ startDate, endDate, category }) {
  const where = {};

  if (startDate || endDate) {
    where.date = {};
    if (startDate) where.date.gte = new Date(startDate);
    if (endDate) where.date.lte = new Date(endDate);
  }

  if (category) {
    where.category = category;
  }

  return prisma.ledgerTransaction.findMany({
    where,
    orderBy: { date: "desc" },
  });
}

module.exports = {
  createTransaction,
  listTransactions,
};
